### PR TITLE
Fix #288 Refresh token : Failed to get refresh token

### LINKED ISSUE #288: Refresh token : Failed to get refresh token

### PR DESCRIPTION
**Pull request by albinpa**

### CODE REVIEW

File: src/v2/handler/onboard/onboard_refresh_token.go [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+		common.HandleError(w, http.StatusBadRequest, err.Error(), err)
+		return
+	}
+
+	client := iam.GetClient()
+
+	var resp refreshTokenResp
+
+	t, err := iam.RefreshToken(tReq.ClientID, tReq.RefreshToken, iam.IamConfig.Realm, client)
+	if err != nil {
```
Comment (georgepadayatti) [inline src/v2/handler/onboard/onboard_refresh_token.go:89]: If `clientId` is equal to consent BB `clientId` then, then the individual/admin is part of consent BB IDP else they are part of external IDP.

**Review by georgepadayatti — CHANGES_REQUESTED** [review]

**Review by georgepadayatti — APPROVED** [review]
